# fly.toml app configuration file for MoneyInputPlayground.
#
# See https://fly.io/docs/reference/configuration/ for the full
# reference.

app = 'elixir-money-input'
primary_region = 'iad'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '15s'
    timeout = '5s'
    grace_period = '5s'
    method = 'get'
    path = '/healthz'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
